spring.application.name=stock-trading-engine



server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/stock_trading_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html

logging.level.root=INFO
logging.level.com.trading=DEBUG
logging.file.name=logs/stock-trading-engine.log